name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger: none

# equivalent trigger
# trigger:
#   branches:
#     include:
#     - master
  
variables:
  name: colin
  
pool:
  vmImage: ubuntu-latest
  
jobs:
- job: helloworld
  steps:
  - script: echo "Hello, $(name)"