trigger: none

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: helloworld
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: connectedServiceName
      serviceConnection: Generic
      method: GET